name: Say hello

on:
  push:
    branches:
      - main 
    
jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo the mesage
        run: echo "Hello world!"
      - name: Echo the date
        run: date
      - run: ls -l