name: Deploy Pipline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cone repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
         node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Linter code
        run: npm run eslint
        

