name: Deploy Pipline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
         node-version: 22.15.0
      - name: Install system dependencies for build
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Clean install Node.js dependencies
        run: |
          rm -rf node_modules
          npm cache clean --force
          rm -f package-lock.json
          npm install --no-audit --no-fund
      - name: Lint code
        run: npm run eslint
      - name: Build project
        run: npm run build
        
        

